version: '3.8'
services:

  postgre:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=MediaFiles
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  # mediafiles:
  #   build: 
  #     context: .
  #   volumes:
  #     - ./:/web_map
  #   ports:
  #     - '8000:8000'
  #   environment:
  #     - SQL_ENGINE=django.db.backends.postgresql
  #     - DB_HOST=postgre
  #     - DB_NAME=MediaFiles
  #     - DB_USER=postgres
  #     - DB_PASS=postgres
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     postgre:
  #       condition: service_healthy
